spring:
  data:
    mongodb:
      username: gilxhon
      password: gilxhon
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
